#!/bin/sh

# Install Homebrew if not found
if test ! $(which brew); then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Fetch the newest version of Homebrew and all formulae
brew update

# Install dependencies with bundle. See ./Brewfile for dependencies.
brew tap homebrew/bundle
brew bundle

# Install oh-my-zsh
if test ! -d "$HOME/.oh-my-zsh"; then 
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# Set macOS preferences
# Run last because this will reload the shell
echo "Enter password to update macOS preferences"
source .macos

exec zsh
